mutation sendOtp($phone: String!, $languageId: LanguageId) {
  sendOtp(phone: $phone, languageId: $languageId) {
    code
    translationCode
    message
    verificationId
  }
}
mutation checkOtp($verificationId: String!, $otp: String!, $contact: String!) {
  checkOtp(verificationId: $verificationId, otp: $otp, contact: $contact) {
    code
    translationCode
    message
    verificationId
  }
}
mutation signUpUser($user: UserIn!, $otpData: OtpInput!, $languageId: LanguageId, $appBrand: AppBrand!) {
  signUpUser(user: $user, otpData: $otpData, languageId: $languageId, appBrand: $appBrand) {
    code
    translationCode
    message
  }
}

mutation utilityIntegrationTest($input: UtilityIntegrationTestInput!) {
  utilityIntegrationTest(input: $input) {
    code
    message
  }
}

mutation verifyEmail($verificationId: String!, $otp: String!, $uuid: String!) {
  verifyEmail(verificationId: $verificationId, otp: $otp, uuid: $uuid) {
    code
    translationCode
    message
  }
}

mutation createPet($pet: PetIn!) {
  createPet(pet: $pet) {
    code
    translationCode
    message
    pet {
      id
      entityType
      name
      birthDate
      species
      breedType
      breeds
      gender
      primaryColor
      weight
      userId
      creationDate
      updateDate
      image {
        id
        url
      }
      neutered
      livingEnvironment
      length
      dateMarkedAsLost
      petProtectionId
    }
  }
}

mutation updatePet($pet: UpdatePetIn!) {
  updatePet(pet: $pet) {
    code
    translationCode
    message
    pet {
      id
      entityType
      name
      birthDate
      species
      breedType
      breeds
      gender
      primaryColor
      weight
      userId
      creationDate
      updateDate
      image {
        id
        url
      }
      neutered
      livingEnvironment
      length
      dateMarkedAsLost
      petProtectionId
    }
  }
}

mutation deletePet($petId: String!) {
  deletePet(petId: $petId) {
    code
    translationCode
    message
  }
}

mutation createPetlinkGps($petlinkGps: PetlinkGpsIn!, $appBrand: AppBrand!) {
  createPetlinkGps(petlinkGps: $petlinkGps, appBrand: $appBrand) {
    code
    translationCode
    message
    petlinkGps {
      id
      entityType
      serialNumber
      petId
      userId
      creationDate
      updateDate
      countryCode
      timezone
      lastKnownPosition {
        lat
        lng
        alt
        radius
        speed
        positionType
        date
      }
      lastKnownStatus {
        battery
        flashlight
        sound
        liveTracking
        geofence
        inGeofence
        energySavingMode
        inEnergySavingZone
        firmwareVersion
        offline
        date
      }
      geofenceCoordinates {
        lat
        lng
      }
      newFirmwareVersion {
        url
        version
      }
      settings {
        activityProfile
        updateFrequency
        enableGpsOnDefault
        optimizationDone
      }
    }
    currentTermEnd
    url
  }
}

mutation updatePetlinkGps($petlinkGps: UpdatePetlinkGpsIn!) {
  updatePetlinkGps(petlinkGps: $petlinkGps) {
    code
    translationCode
    message
    petlinkGps {
      id
      entityType
      serialNumber
      petId
      userId
      creationDate
      updateDate
      countryCode
      timezone
      lastKnownPosition {
        lat
        lng
        alt
        radius
        speed
        positionType
        date
      }
      lastKnownStatus {
        battery
        flashlight
        sound
        liveTracking
        geofence
        inGeofence
        energySavingMode
        inEnergySavingZone
        firmwareVersion
        offline
        date
      }
      geofenceCoordinates {
        lat
        lng
      }
      newFirmwareVersion {
        version
        url
      }
      settings {
        activityProfile
        updateFrequency
        enableGpsOnDefault
        optimizationDone
      }
      subscriptionId
      subscriptionIsActive
      logEnabled
    }
  }
}

mutation resetPetlinkGps($id: String!) {
  resetPetlinkGps(id: $id) {
    code
    translationCode
    message
  }
}

mutation updateBillingInfo($updateBillingInfoInput: UpdateBillingInfoInput!) {
  updateBillingInfo(updateBillingInfoInput: $updateBillingInfoInput) {
    code
    translationCode
    message
  }
}

mutation updatePetProtectionData($petProtectionId: String!, $owner: PetProtectionOwnerIn!, $pet: PetProtectionPetIn!) {
  updatePetProtectionData(petProtectionId: $petProtectionId, owner: $owner, pet: $pet) {
    code
    translationCode
    message
    petProtection {
      id
      petId
      userId
      chargebeeSubscriptionId
      currentTermStart
      currentTermEnd
      status
      petOwner {
        name
        surname
        email
        fiscalCode
        city
        zipCode
        streetAddress
        countryCode
        provinceCode
        homePhone
        mobilePhone
      }
      pet {
        species
        breed
        gender
        name
        birthDate
        microchip
      }
      petFlag {
        country
        age
      }
      codiceTessera
      fileName
      name
      price
      currencyCode
      period
      periodUnit
      reservedCoupon
      reservedCouponPercent
      customerServiceContact
      card {
        expiryMonth
        expiryYear
        maskedNumber
        type
        brand
        paymentMethod
      }
    }
  }
}

mutation stopRenewingSubscription($subscriptionId: String!, $appBrand: AppBrand!, $cancelReason: String!, $cancelReasonCode: CancelReasonCodeEnum!) {
  stopRenewingSubscription(subscriptionId: $subscriptionId, appBrand: $appBrand, cancelReason: $cancelReason, cancelReasonCode: $cancelReasonCode) {
    code
    translationCode
    message
  }
}

mutation updateUser($user: UpdateUserIn!) {
  updateUser(user: $user) {
    code
    translationCode
    message
    user {
      id
      entityType
      name
      surname
      email
      phone
      birthDate
      gender
      city
      countryCode
      zipCode
      streetAddress
      stateCode
      languageId
      timezone
      image {
        id
        url
      }
      creationDate
      updateDate
    }
  }
}

mutation deleteUser($id: String!) {
  deleteUser(id: $id) {
    code
    translationCode
    message
  }
}

mutation sendCommand($command: Command!) {
  sendCommand(command: $command) {
    code
    translationCode
    message
  }
}

mutation sendSetting($setting: Setting!) {
  sendSetting(setting: $setting) {
    code
    translationCode
    message
    petlinkGps {
      id
      entityType
      serialNumber
      petId
      userId
      creationDate
      updateDate
      countryCode
      timezone
      lastKnownPosition {
        lat
        lng
        alt
        radius
        speed
        positionType
        date
      }
      lastKnownStatus {
        battery
        flashlight
        sound
        liveTracking
        geofence
        inGeofence
        energySavingMode
        inEnergySavingZone
        firmwareVersion
        offline
        date
      }
      geofenceCoordinates {
        lat
        lng
      }
      settings {
        updateFrequency
        enableGpsOnDefault
      }
      subscriptionId
      subscriptionIsActive
      endOfLifeDevice
    }
    energySavingZone {
      entityType
      id
      name
      icon
      ssid
      bssid
      userId
      position {
        lat
        lng
      }
      radius
      creationDate
      updateDate
    }
  }
}