mutation sendOtp($phone: String!, $languageId: LanguageId) {
  sendOtp(phone: $phone, languageId: $languageId) {
    code
    translationCode
    message
    verificationId
  }
}
mutation checkOtp($verificationId: String!, $otp: String!, $contact: String!) {
  checkOtp(verificationId: $verificationId, otp: $otp, contact: $contact) {
    code
    translationCode
    message
    verificationId
  }
}
mutation signUpUser(
  $user: UserIn!
  $otpData: OtpInput!
  $languageId: LanguageId
  $appBrand: AppBrand
) {
  signUpUser(
    user: $user
    otpData: $otpData
    languageId: $languageId
    appBrand: $appBrand
  ) {
    code
    translationCode
    message
  }
}

mutation utilityIntegrationTest($input: UtilityIntegrationTestInput!) {
  utilityIntegrationTest(input: $input) {
    code
    message
  }
}

mutation verifyEmail($verificationId: String!, $otp: String!, $uuid: String!) {
  verifyEmail(verificationId: $verificationId, otp: $otp, uuid: $uuid) {
    code
    translationCode
    message
  }
}

mutation createPet($pet: PetIn!) {
  createPet(pet: $pet) {
    code
    translationCode
    message
    pet {
      id
      entityType
      name
      birthDate
      species
      breedType
      breeds
      gender
      primaryColor
      weight
      userId
      creationDate
      updateDate
      image {
        id
        url
      }
      neutered
      livingEnvironment
      length
      dateMarkedAsLost
      petProtectionId
    }
  }
}

mutation updatePet($pet: UpdatePetIn!) {
  updatePet(pet: $pet) {
    code
    translationCode
    message
    pet {
      id
      entityType
      name
      birthDate
      species
      breedType
      breeds
      gender
      primaryColor
      weight
      userId
      creationDate
      updateDate
      image {
        id
        url
      }
      neutered
      livingEnvironment
      length
      dateMarkedAsLost
      petProtectionId
    }
  }
}

mutation deletePet($petId: String!) {
  deletePet(petId: $petId) {
    code
    translationCode
    message
  }
}