query getUser {
  getUser {
    code
    message
    translationCode
    user {
      birthDate
      chargebeeId
      city
      contactVerified {
        email
        phone
      }
      countryCode
      creationDate
      email
      entityType
      haveMicrochip
      gender
      id
      image {
        id
        url
      }
      languageId
      name
      mobileDevices {
        os
        registrationToken
        serialNumber
      }
      notificationSettings {
        email
        energySavingZone {
          push
        }
        push
        sms
      }
      phone
      safetyTermsCat
      settings {
        liveDistance
        liveSpeed
        liveTrack
      }
      stateCode
      streetAddress
      surname
      timezone
      updateDate
      zipCode
    }
  }
}

query checkContact($contact: String!, $contactType: ContactType!) {
  checkContact(contact: $contact, contactType: $contactType) {
    code
    translationCode
    message
  }
}

query getPet($id: String!) {
  getPet(id: $id) {
    code
    translationCode
    message
    pet {
      id
      name
      birthDate
      species
      breedType
      breeds
      gender
      primaryColor
      weight
      userId
      creationDate
      updateDate
      neutered
      length
      dateMarkedAsLost
      petProtectionId
    }
  }
}

query getPets {
  getPets {
    code
    message
    pets {
      id
      name
      birthDate
      species
      breedType
      breeds
      gender
      primaryColor
      weight
      userId
      creationDate
      updateDate
      neutered
      length
      dateMarkedAsLost
      petProtectionId
    }
  }
}

query getColors($species: SpeciesEnum!, $languageId: LanguageId) {
  getColors(species: $species, languageId: $languageId) {
    code
    message
    translationCode
    items {
      code
      name
    }
  }
}

query getBreed($species: SpeciesEnum!, $languageId: LanguageId) {
  getBreed(species: $species, languageId: $languageId) {
    code
    message
    translationCode
    items {
      breedName
      code
      species
    }
  }
}

query getPetlinkGps($id: String!) {
  getPetlinkGps(id: $id) {
    code
    translationCode
    message
    petlinkGps {
      id
      entityType
      serialNumber
      petId
      userId
      creationDate
      updateDate
      countryCode
      timezone
      lastKnownPosition {
        lat
        lng
        alt
        radius
        speed
        positionType
        date
      }
      lastKnownStatus {
        battery
        flashlight
        sound
        liveTracking
        geofence
        inGeofence
        energySavingMode
        inEnergySavingZone
        firmwareVersion
        offline
        date
      }
      geofenceCoordinates {
        lat
        lng
      }
      newFirmwareVersion {
        version
        url
      }
      settings {
        activityProfile
        updateFrequency
        enableGpsOnDefault
        optimizationDone
      }
      subscriptionId
      subscriptionIsActive
      logEnabled
    }
  }
}

query getSubscriptionPlans(
  $productId: String
  $countryCode: String
  $serialNumber: String
) {
  getSubscriptionPlans(
    productId: $productId
    countryCode: $countryCode
    serialNumber: $serialNumber
  ) {
    code
    translationCode
    message
    plans {
      itemId
      pricings {
        addonPricings {
          id
          name
          externalName
          itemId
          price
          period
          currencyCode
          periodUnit
          itemFamilyId
          status
          trialPeriod
          trialPeriodUnit
        }
        id
        name
        externalName
        itemId
        price
        period
        currencyCode
        periodUnit
        itemFamilyId
        status
        trialPeriod
        trialPeriodUnit
      }
    }
    careProtectionPlans {
      itemId
      pricings {
        id
        name
        externalName
        itemId
        price
        period
        currencyCode
        periodUnit
        itemFamilyId
        status
        trialPeriod
        trialPeriodUnit
      }
    }
    trialDuration
    paymentMethodRequired
    coupon {
      id
      name
      discountType
      discountPercentage
      discountAmount
      discountQuantity
      currencyCode
    }
  }
}

query getBillingInfo {
  getBillingInfo {
    code
    translationCode
    message
    billingInfo {
      firstName
      lastName
      email
      phone
      address
      city
      stateCode
      state
      country
      zip
    }
  }
}

query getSubscriptionPlanPricing(
  $planPriceId: String!
  $careProtectionPlanId: String
  $addonPriceIds: [String!]
  $countryCode: String!
  $productId: String!
) {
  getSubscriptionPlanPricing(
    planPriceId: $planPriceId
    careProtectionPlanId: $careProtectionPlanId
    addonPriceIds: $addonPriceIds
    countryCode: $countryCode
    productId: $productId
  ) {
    code
    translationCode
    message
    pricing {
      id
      name
      externalName
      itemId
      price
      period
      currencyCode
      periodUnit
      itemFamilyId
      status
      trialPeriod
      trialPeriodUnit
    }
    careProtectionPricing {
      id
      name
      externalName
      itemId
      price
      period
      currencyCode
      periodUnit
      itemFamilyId
      status
      trialPeriod
      trialPeriodUnit
    }
    trialDuration
    paymentMethodRequired
    coupon {
      id
      name
      discountType
      discountPercentage
      discountAmount
      discountQuantity
      currencyCode
    }
  }
}

query getSubscriptionByProductId($productId: String!) {
  getSubscriptionByProductId(productId: $productId) {
    code
    translationCode
    message
    subscription {
      id
      status
      currentTermStart
      currentTermEnd
      nextBillingAt
      card {
        expiryMonth
        expiryYear
        maskedNumber
        type
        brand
        paymentMethod
      }
      currencyCode
      paymentStatus
      planChangeNotAllowed
      subscriptionItems {
        amount
        name
        itemPriceId
        itemType
        quantity
        unitPrice
        itemId
      }
      billingPeriod
      billingPeriodUnit
      addonToStopIds
    }
  }
}

query getPetProtection($petProtectionId: String!) {
  getPetProtection(petProtectionId: $petProtectionId) {
    code
    translationCode
    message
    petProtection {
      id
      petId
      userId
      chargebeeSubscriptionId
      currentTermStart
      currentTermEnd
      status
      petOwner {
        name
        surname
        email
        fiscalCode
        city
        zipCode
        streetAddress
        countryCode
        provinceCode
        homePhone
        mobilePhone
      }
      pet {
        species
        breed
        gender
        name
        birthDate
        microchip
      }
      petFlag {
        country
        age
      }
      codiceTessera
      fileName
      name
      price
      currencyCode
      period
      periodUnit
      reservedCoupon
      reservedCouponPercent
      customerServiceContact
      card {
        expiryMonth
        expiryYear
        maskedNumber
        type
        brand
        paymentMethod
      }
    }
  }
}

# mange User credentials #

#CHANGE flows (authenticated - JWT required)

mutation changePassword($oldPassword: String!, $password: String!) {
  changePassword(oldPassword: $oldPassword, password: $password) {
    code
    translationCode
    message
  }
}

mutation updateEmailUser($email: String!, $languageId: LanguageId, $appBrand: AppBrand!) {
  updateEmailUser(email: $email, languageId: $languageId, appBrand: $appBrand) {
    code
    translationCode
    message
  }
}

mutation updatePhoneNumberUser($phone: String!, $languageId: LanguageId, $verificationId: String!, $otp: String!) {
  updatePhoneNumberUser(phone: $phone, languageId: $languageId, verificationId: $verificationId, otp: $otp) {
    code
    translationCode
    message
  }
}

#FORGOT/RECOVERY flows (public - NO auth)

mutation sendOtpForgotPassword($contact: String!, $languageId: LanguageId) {
  sendOtpForgotPassword(contact: $contact, languageId: $languageId) {
    code
    translationCode
    message
    verificationId
  }
}

mutation changeForgotPassword($otp: String!, $verificationId: String!, $password: String!) {
  changeForgotPassword(otp: $otp, verificationId: $verificationId, password: $password) {
    code
    translationCode
    message
  }
}

mutation forgotEmail($productNumber: String!, $entityType: ProductTypeEnum, $languageId: LanguageId) {
  forgotEmail(productNumber: $productNumber, entityType: $entityType, languageId: $languageId) {
    code
    translationCode
    message
  }
}