
query getUser {
  getUser {
    code
    message
    translationCode
    user {
      birthDate
      chargebeeId
      city
      contactVerified {
        email
        phone
      }
      countryCode
      creationDate
      email
      entityType
      haveMicrochip
      gender
      id
      image {
        id
        url
      }
      languageId
      name
      mobileDevices {
        os
        registrationToken
        serialNumber
      }
      notificationSettings {
        email
        energySavingZone {
          push
        }
        push
        sms
      }
      phone
      safetyTermsCat
      settings {
        liveDistance
        liveSpeed
        liveTrack
      }
      stateCode
      streetAddress
      surname
      timezone
      updateDate
      zipCode
    }
  }
}

query checkContact($contact: String!, $contactType: ContactType!) {
  checkContact(contact: $contact, contactType: $contactType) {
    code
    translationCode
    message
  }
}


query getPet($id: String!) {
  getPet(id: $id) {
    code
    translationCode
    message
    pet {
      id
      name 
      birthDate
      species 
      breedType 
      breeds
      gender 
      primaryColor
      weight
      userId 
      creationDate 
      updateDate 
      neutered
      length
      dateMarkedAsLost
    }
  }
}

query getPets {
  getPets {
    code
    message
    pets {
      id
      name
      birthDate
      species
      breedType
      breeds
      gender
      primaryColor
      weight
      userId
      creationDate
      updateDate
      neutered
      length
      dateMarkedAsLost
    }
  }
}

query getColors($species: SpeciesEnum!, $languageId: LanguageId) {
  getColors(species: $species, languageId: $languageId) {
    code
    message
    translationCode
    items {
      code
      name
    }
  }
}


query getBreed($species: SpeciesEnum!, $languageId: LanguageId) {
  getBreed(species: $species, languageId: $languageId) {
    code
    message
    translationCode
    items {
      breedName
      code
      species
    }
  }
}

query getPetlinkGps($id: String!) {
  getPetlinkGps(id: $id) {
    code
    translationCode
    message
    petlinkGps {
      id
      entityType
      serialNumber
      petId
      userId
      creationDate
      updateDate
      countryCode
      timezone
      lastKnownPosition {
        lat
        lng
        alt
        radius
        speed
        positionType
        date
      }
      lastKnownStatus {
        battery
        flashlight
        sound
        liveTracking
        geofence
        inGeofence
        energySavingMode
        inEnergySavingZone
        firmwareVersion
        offline
        date
      }
      geofenceCoordinates {
        lat
        lng
      }
      newFirmwareVersion {
        version
        url
      }
      settings {
        activityProfile
        updateFrequency
        enableGpsOnDefault
        optimizationDone
      }
      subscriptionId
      subscriptionIsActive
      logEnabled
    }
  }
}