# No mutations currently used
mutation createUser($user: CreateUserInput!) {
    createUser(user: $user) {
        code
        message
        translationCode
        user {
            id
            name
            surname
            email
            phone
            role
            username
            active
            deviceVisibility
            vodafoneCountryVisibility
            creationDate
            updateDate
        }
    }
}

mutation updateUser($userInfo: UpdateUserInput!) {
  updateUser(userInfo: $userInfo) {
    code
    message
    translationCode
    user {
      id
      name
      surname
      email
      phone
      role
      username
      active
      deviceVisibility
      vodafoneCountryVisibility
      creationDate
      updateDate
    }
  }
}

mutation deleteUser($id: String!) {
  deleteUser(id: $id) {
    code
    message
    translationCode
  }
}

mutation updateCustomer($customerId: String!, $updateCustomer: UpdateCustomerInput!) {
  updateCustomer(customerId: $customerId, updateCustomer: $updateCustomer) {
    code
    message
    translationCode
    customer {
      id
      name
      surname
      email
      phone
      countryCode
    }
  }
}

mutation deleteCustomer($id: String!) {
  deleteCustomer(id: $id) {
    code
    message
    translationCode
  }
}

mutation resetPetlinkGps($id: String!) {
  resetPetlinkGps(id: $id) {
    code
    message
    translationCode
  }
}