"""This directive allows results to be deferred during execution"""
directive @defer on FIELD

"""
Tells the service this field/object has access authorized by an OIDC token.
"""
directive @aws_oidc on OBJECT | FIELD_DEFINITION

"""
Tells the service which subscriptions will be published to when this mutation is
called. This directive is deprecated use @aws_susbscribe directive instead.
"""
directive @aws_publish(
  """
  List of subscriptions which will be published to when this mutation is called.
  """
  subscriptions: [String]
) on FIELD_DEFINITION

"""Tells the service which mutation triggers this subscription."""
directive @aws_subscribe(
  """
  List of mutations which will trigger this subscription when they are called.
  """
  mutations: [String]
) on FIELD_DEFINITION

"""
Tells the service this field/object has access authorized by an API key.
"""
directive @aws_api_key on OBJECT | FIELD_DEFINITION

"""Directs the schema to enforce authorization on a field"""
directive @aws_auth(
  """List of cognito user pool groups which have access on this field"""
  cognito_groups: [String]
) on FIELD_DEFINITION

"""
Tells the service this field/object has access authorized by sigv4 signing.
"""
directive @aws_iam on OBJECT | FIELD_DEFINITION

"""
Tells the service this field/object has access authorized by a Cognito User Pools token.
"""
directive @aws_cognito_user_pools(
  """List of cognito user pool groups which have access on this field"""
  cognito_groups: [String]
) on OBJECT | FIELD_DEFINITION

"""
Tells the service this field/object has access authorized by a Lambda Authorizer.
"""
directive @aws_lambda on OBJECT | FIELD_DEFINITION

type Activities {
  serialNumber: String
  petId: String
  timestamp: Float

  """  dog and cat"""
  walk: Float
  sleep: Float
  steps: Float
  calories: Float
  onTheMove: Float

  """  only dog"""
  play: Float
  run: Float

  """  only cat"""
  feed: Float
  jumps: Float
  highMovement: Float
  grooming: Float
}

enum ActivityProfileEnum {
  SEDENTARY
  MODERATELY_ACTIVE
  VERY_ACTIVE
}

type ActivityReport {
  serialNumber: String
  petId: String!
  activitiesLevel: Float
  walk: ActivityValue!
  sleep: ActivityValue!
  calories: ActivityValue!
  steps: ActivityValue!
  play: ActivityValue!
  run: ActivityValue!
  onTheMove: ActivityValue!
}

type ActivityReportAverageCat {
  petId: String!
  activitiesLevel: Float
  walk: ActivityValue!
  sleep: ActivityValue!
  calories: ActivityValue!
  steps: ActivityValue!
  feed: ActivityValue!
  jumps: ActivityValue!
  onTheMove: ActivityValue!
  highMovement: ActivityValue!
  grooming: ActivityValue!
}

type ActivityReportCat {
  serialNumber: String
  petId: String!
  activitiesLevel: Float
  walk: ActivityValueCat!
  sleep: ActivityValueCat!
  calories: ActivityValueCat!
  steps: ActivityValueCat!
  feed: ActivityValueCat!
  jumps: ActivityValueCat!
  onTheMove: ActivityValueCat!
  highMovement: ActivityValueCat!
  grooming: ActivityValueCat!
}

type ActivityValue {
  value: Float!
  goal: Float!
}

type ActivityValueCat {
  value: Float!
  goal: GoalRange!
}

type AddonPricing {
  id: String!
  name: String!
  externalName: String
  itemId: String!
  price: Float
  period: Float
  currencyCode: String!
  periodUnit: String
  itemFamilyId: String
  status: String
  trialPeriod: Int
  trialPeriodUnit: String
}

enum AppBrand {
  KIPPY
  PETLINK
}

"""
The `AWSJSON` scalar type provided by AWS AppSync, represents a JSON string that
complies with [RFC 8259](https://tools.ietf.org/html/rfc8259).  Maps like
"**{\\"upvotes\\": 10}**", lists like "**[1,2,3]**", and scalar values like
"**\\"AWSJSON example string\\"**", "**1**", and "**true**" are accepted as
valid JSON and will automatically be parsed and loaded in the resolver mapping
templates as Maps, Lists, or Scalar values rather than as the literal input
strings.  Invalid JSON strings like "**{a: 1}**", "**{'a': 1}**" and "**Unquoted
string**" will throw GraphQL validation errors.
"""
scalar AWSJSON

type BillingInfo {
  firstName: String
  lastName: String
  email: String
  phone: String
  address: String
  city: String
  stateCode: String
  state: String
  country: String
  zip: String
}

input BillingInfoInput {
  address: String!
  city: String!
  state: String
  zip: String!
  country: String!
}

type Breed {
  code: String!
  species: SpeciesEnum!
  breedName: String!
}

enum BreedTypeEnum {
  PUREBREED
  MIXED_BREED
}

enum CancelReasonCodeEnum {
  DO_NOT_USE
  DO_NOT_WORK_PROPERLY
  MISSING_PET
  TOO_EXPENSIVE
  NOT_SUITABLE
  OTHER
}

type Card {
  expiryMonth: Int
  expiryYear: Int
  maskedNumber: String
  type: String
  brand: String
  paymentMethod: String!
}

type CareProtectionPlan {
  itemId: String!
  pricings: [Pricing]!
}

type Color {
  code: String!
  name: String!
}

input Command {
  commandType: CommandEnum!
  id: String!
  duration: Int
  modeType: ModeType
}

enum CommandEnum {
  LIVE_TRACKING
  FLASHLIGHT
  SOUND
  LIVE_TRACKING_TEST
}

enum ContactType {
  PHONE
  EMAIL
}

type ContactVerified {
  email: Boolean
  phone: Boolean
}

type ContentMessage {
  position: Coordinates
  name: String!
  contact: String!
  message: String!
  petName: String!
}

type Coordinates {
  lat: Float!
  lng: Float!
}

input CoordinatesIn {
  lat: Float
  lng: Float
}

type CountryState {
  code: String!
  name: String!
  gpsOptimizationCommand: GpsOptimizationCommand
}

type Coupon {
  id: String!
  name: String!
  discountType: String!
  discountPercentage: Int
  discountAmount: Int
  discountQuantity: Int
  currencyCode: String
}

type Device {
  itemId: String!
  serialNumber: String!
  deviceType: DeviceTypeEnum!
  activated: Boolean!
}

type DevicePrice {
  id: String!
  deviceType: DeviceTypeEnum!
  price: Float!
  period: Float
  periodUnit: String
  discountPercentage: Int!
  currencyCode: String!
  countryCode: String!
}

enum DeviceTypeEnum {
  CAT
  DOG
  EVO
}

type DiscoutItem {
  chargebeeInvoiceItemId: String!
  amount: Float!
  couponId: String!
  discountPercentage: Float
  discountType: String!
}

type EndOfLife {
  id: String!
  step: String!
  userId: String!
  productId: String!
  serialNumber: String!
  devicePriceId: String
  subscriptionId: String
  priceIds: [String!]
  shopUrl: String
  shippingAddress: ShippingAddress
}

input EndOfLifeIn {
  step: String!
  userId: String!
  productId: String!
  serialNumber: String!
  devicePriceId: String
  subscriptionId: String
  priceIds: [String!]
  shopUrl: String
  shippingAddress: ShippingAddressIn
}

type EnergySavingZone {
  entityType: EntityTypeEnum!
  id: String!
  name: String!
  icon: String!
  ssid: String!
  bssid: String!
  userId: String!
  position: Coordinates!
  radius: Float!
  creationDate: String!
  updateDate: String!
}

input EnergySavingZoneIn {
  entityType: EntityTypeEnum!
  ssid: String!
  bssid: String!
  icon: String!
  name: String!
  position: CoordinatesIn!
  radius: Float!
}

enum EntityTypeEnum {
  USER
  PET
  PETLINK_MICROCHIP
  PETLINK_GPS
  PETLINK_QR_TAG
  PET_HISTORY_EVENT
  ENERGY_SAVING_ZONE
  GEOFENCE
  ACTIVITY
  SUBSCRIPTION
}

type EszNotificationPreferences {
  push: Boolean!
}

input EszNotificationPreferencesIn {
  push: Boolean!
}

input EszNotificationsInput {
  push: Boolean!
}

enum Gender {
  MALE
  FEMALE
}

type Geofence {
  id: String!
  entityType: EntityTypeEnum!
  creationDate: String!
  updateDate: String!
  userId: String!
  name: String!
  position: [Coordinates!]!
  devices: [String]
}

input GeofenceIn {
  name: String!
  position: [CoordinatesIn!]!
}

type GoalRange {
  min: Float!
  max: Float!
}

type GpsMessagePosition {
  messageType: GpsMessageType!
  id: String!
  position: GpsPosition!
}

input GpsMessagePositionIn {
  messageType: GpsMessageType!
  id: String!
  position: GpsPositionIn!
}

type GpsMessageStatus {
  messageType: GpsMessageType!
  id: String!
  status: GpsStatus!
}

input GpsMessageStatusIn {
  messageType: GpsMessageType!
  id: String!
  status: GpsStatusIn!
}

enum GpsMessageType {
  LIVE_TRACKING
  LAST_POSITION
  STATUS
}

type GpsOptimizationCommand {
  rfTecnology: String!
  rfBand: String!
}

type GpsPosition {
  lat: Float!
  lng: Float!
  alt: Float
  radius: Float!
  speed: Float
  positionType: PositionType!
  date: String!
}

input GpsPositionIn {
  lat: Float!
  lng: Float!
  alt: Float
  radius: Float!
  speed: Float
  positionType: PositionType!
  date: String!
}

type GpsSettings {
  activityProfile: ActivityProfileEnum
  updateFrequency: Int!
  enableGpsOnDefault: Boolean!
  optimizationDone: Boolean
}

input GpsSettingsIn {
  activityProfile: ActivityProfileEnum
  updateFrequency: Int
  enableGpsOnDefault: Boolean
}

type GpsStatus {
  battery: Int!
  flashlight: StatusState!
  sound: StatusState!
  liveTracking: StatusState!
  geofence: StatusState!
  inGeofence: Boolean
  energySavingMode: StatusState!
  inEnergySavingZone: Boolean
  firmwareVersion: String!
  offline: Boolean
  date: String!
}

input GpsStatusIn {
  battery: Int!
  flashlight: StatusState!
  sound: StatusState!
  liveTracking: StatusState!
  geofence: StatusState!
  inGeofence: Boolean
  energySavingMode: StatusState!
  inEnergySavingZone: Boolean
  firmwareVersion: String!
  offline: Boolean
  date: String!
}

enum HighlightEnum {
  HIDE
  ABOVE_AVERAGE
  BELOW_AVERAGE
  ABOVE_THRESHOLD
  BELOW_THRESHOLD
  AVERAGE
}

type Highlights {
  highMovement: HighlightEnum
  jumps: HighlightEnum
  grooming: HighlightEnum
  feed: HighlightEnum
  isStressed: HighlightEnum
}

input HostedPageOptionsInput {
  redirectUrl: String
  layout: LayoutPageEnum
}

type Image {
  id: String!
  url: String
}

enum ImageUploadType {
  USER
  PET
}

type InvoiceItemShortInfo {
  amount: Int!
  description: String!
  itemType: String!
  itemId: String!
  quantity: Int!
  unitPrice: Int!
}

enum InvoiceReasonCodeEnum {
  product_unsatisfactory
  service_unsatisfactory
  order_change
  order_cancellation
  waiver
  other
}

type InvoiceShortInfo {
  id: String!
  total: Float!
  currencyCode: String!
  status: InvoiceStatusEnum!
  creationDate: String!
  items: [InvoiceItemShortInfo!]!
  discountItems: [DiscoutItem!]
}

enum InvoiceStatusEnum {
  paid
  posted
  payment_due
  not_paid
  voided
  pending
  paid_externally
  non_paying
}

enum LanguageId {
  IT
  EN
  FR
  ES
  DE
}

enum LayoutPageEnum {
  in_app
  full_page
}

enum LikeType {
  LIKE
  DISLIKE
}

input LostIn {
  lostDate: String!
  countryCode: String!
  zipCode: String!
  publishInLostPage: Boolean!
  showPhoneNumber: Boolean!
  showEmailAddress: Boolean!
  imageId: String
  note: String
}

type LostInfo {
  id: String!
  petId: String!
  userId: String!
  creationDate: String!
  updateDate: String!
  lostDate: String!
  countryCode: String!
  zipCode: String!
  note: String
  publishInLostPage: Boolean!
  showPhoneNumber: Boolean!
  showEmailAddress: Boolean!
  image: Image
}

input MessageFoundPetIn {
  name: String!
  contact: String!
  message: String!
  serialNumber: String!
  position: Position
}

type MobileDevice {
  serialNumber: String!
  registrationToken: String!
  os: MobileOsEnum!
}

enum MobileOsEnum {
  ANDROID
  IOS
}

enum ModeType {
  BLE
  SENTINEL
}

type Mutation {
  sendOtp(phone: String!, languageId: LanguageId): ResponseOtp!
  checkOtp(verificationId: String!, otp: String!, contact: String!): ResponseOtp!
  signUpUser(user: UserIn!, otpData: OtpInput!, languageId: LanguageId, appBrand: AppBrand!): Response!
  deleteUser(id: String): Response!
  updateUser(user: UpdateUserIn!): ResponseUser!
  updateEmailUser(email: String!, languageId: LanguageId, appBrand: AppBrand!): Response!
  updatePhoneNumberUser(phone: String!, languageId: LanguageId, verificationId: String!, otp: String!): Response!
  forgotEmail(productNumber: String!, entityType: ProductTypeEnum, languageId: LanguageId): Response
  sendOtpForgotPassword(contact: String!, languageId: LanguageId): ResponseOtp!
  changeForgotPassword(otp: String!, verificationId: String!, password: String!): Response!
  changePassword(oldPassword: String!, password: String!): Response!

  """  add sub w/uuid from verifyEmail"""
  sendTokenEmail(email: String, languageId: LanguageId, appBrand: AppBrand!): Response!
  verifyEmail(verificationId: String!, otp: String!, uuid: String!): Response
  updateNotificationSettings(notificationSettings: UpdateNotificationSettingsInput!): ResponseNotificationSettings!
  deleteRegistrationToken(mobileDevice: String!): Response!
  createPet(pet: PetIn!): ResponsePet!
  updatePet(pet: UpdatePetIn!): ResponsePet!
  deletePet(petId: String!): Response!
  createPetlinkQrTag(petlinkQrTag: PetlinkQrTagIn!): ResponsePetlinkQrTag!
  createPetlinkMicrochip(petlinkMicrochip: PetlinkMicrochipIn!): ResponsePetlinkMicrochip!
  createPetlinkGps(petlinkGps: PetlinkGpsIn!, appBrand: AppBrand!): ResponseCreatePetlinkGps!
  removeProduct(productId: String!): Response!

  """  TODO: rename in deleteProduct"""
  updatePetlinkGps(petlinkGps: UpdatePetlinkGpsIn!): ResponsePetlinkGps!
  resetPetlinkGps(id: String!): Response!
  replacement(productId: String!, newSerialNumber: String!, entityType: ProductTypeEnum!): ResponseReplacement!
  setPetIsLost(petId: String!, lostIn: LostIn!): ResponseSetPetIsLost!
  setOptimizationDone(productId: String!): Response!
  setSafetyTermsCat: Response!
  setArcaPlanetTerms: Response!
  qrTagHasBeenScanned(petlinkQrTag: String!): Response!
  sendMessageFoundPet(message: MessageFoundPetIn!): Response!
  setPetIsFound(petId: String!): ResponseSetPetIsFound!
  pushGpsMessagePositionBLE(productId: String!, position: GpsPositionIn!): Response!
  sendCommand(command: Command!): Response!
  sendSetting(setting: Setting!): ResponseSendSetting!
  createEnergySavingZone(energySavingZone: EnergySavingZoneIn!): ResponseEnergySavingZone!
  updateEnergySavingZone(energySavingZone: UpdateEnergySavingZoneIn!): ResponseEnergySavingZone!
  deleteEnergySavingZone(id: String!): Response!
  isActiveEnergySavingZone(id: String!, isActive: Boolean!): Response!
  createGeofence(geofence: GeofenceIn!): ResponseGeofence!
  updateGeofence(geofence: UpdateGeofenceIn!): ResponseGeofence!
  deleteGeofence(id: String!): Response!
  appKeepAlive(productIds: [String!]!): Response!

  """  cct"""
  updateUserContact(userId: String!, contact: String!, contactType: ContactType!, appBrand: AppBrand!): Response!

  """  sso"""
  setSsoToken(productId: String, appBrand: AppBrand!, pageType: PageTypeEnum!): ResponseSsoUrl!

  """  subscriptions"""
  updateBillingInfo(updateBillingInfoInput: UpdateBillingInfoInput!): Response!
  updatePaymentSources: ResponseManagePaymentSources!
  stopRenewingSubscription(subscriptionId: String!, cancelReason: String!, cancelReasonCode: CancelReasonCodeEnum!, appBrand: AppBrand!): Response
  stopRenewingAddon(subscriptionId: String!, itemPriceIds: [String!]!): Response

  """
   refundInvoice(invoiceId: String!, refundAmount: Float!, reasonCode:
  InvoiceReasonCodeEnum!): Response @aws_cognito_user_pools @aws_iam
  """
  activateDeviceInOrder(deviceId: String!): Response
  addGpsPromotion(deviceId: String!, promotion: PromotionInput!): Response

  """  subscription publishers"""
  publishOnGpsMessagePosition(gpsPosition: GpsMessagePositionIn!): GpsMessagePosition!
  publishOnGpsMessageStatus(gpsStatus: GpsMessageStatusIn!): GpsMessageStatus!
  publishOnSubscriptionStatus(subscriptionStatus: SubscriptionMessageStatusIn!): SubscriptionMessageStatus!

  """  end of life"""
  updateEndOfLife(eolId: String, deviceId: String, input: EndOfLifeIn): ResponseUpdateEndOfLife!

  """  newsletter"""
  registerToNewsletter(email: String!): Response!
  logDisabled(deviceId: String!): Response
  updatePetProtectionData(petProtectionId: String!, owner: PetProtectionOwnerIn!, pet: PetProtectionPetIn!): ResponseUpdatePetProtectionData

  """  test suite"""
  utilityIntegrationTest(input: UtilityIntegrationTestInput!): ResponseUtilityIntegrationTest!
}

type NewFirmwareVersion {
  url: String!
  version: String!
}

type Notification {
  userId: String
  petId: String
  productId: String
  languageId: String
  date: String!
  type: String!
  action: String!
  actionType: String!
  data: AWSJSON
  contact: String
  to: String
}

type NotificationSettings {
  push: Boolean!
  email: Boolean!
  sms: Boolean!
  energySavingZone: EszNotificationPreferences!
}

input NotificationSettingsIn {
  energySavingZone: EszNotificationPreferencesIn!
}

type Order {
  id: String!
  firstName: String!
  lastName: String!
  phone: String!
  email: String!
  country: String!
  state: String
  devices: [Device!]!
}

input OtpInput {
  otp: String!
  verificationId: String!
}

enum PageTypeEnum {
  PET_PROFILE
  PAYMENT_METHOD
  EOL
}

type Pagination {
  pageSize: Int!
  totalPage: Int!
  totalItems: Int!
  currentPage: Int!
}

input PaginationInput {
  pageSize: Int
  pageNumber: Int
}

enum PaymentSourceStatus {
  valid
  expiring
  expired
  invalid
  pending_verification
}

enum PaymentStatusTypeEnum {
  SUCCEEDED
  FAILED
  PENDING
}

type Pet {
  id: String!
  entityType: EntityTypeEnum!
  name: String!
  birthDate: String
  species: String!
  breedType: String!
  breeds: [String!]!
  gender: String!
  primaryColor: String
  weight: Float
  userId: String!
  creationDate: String!
  updateDate: String!
  image: Image
  neutered: Boolean
  livingEnvironment: PetLivingEnvironment
  length: Float
  dateMarkedAsLost: String
  petProtectionId: String
}

type PetCheckMicrochip {
  name: String!
  species: String!
  breeds: [String!]!
  primaryColor: String
}

type PetHistoryEvent {
  id: String!
  entityType: EntityTypeEnum!
  creationDate: String!
  eventType: PetHistoryEventTypeEnum!
  petId: String!
  date: String!
  extra: PetHistoryExtra
}

enum PetHistoryEventTypeEnum {
  PET_BORN
  PET_PROFILE_CREATED
  PET_PROFILE_UPDATED
  GEOFENCE_ACTIVE
  GEOFENCE_OUT
  GEOFENCE_NO_PET
  ENERGY_SAVING_ZONE_IN
  ENERGY_SAVING_ZONE_OUT
  ENERGY_SAVING_ZONE_ACTIVE
  DEVICE_BATTERY
  DEVICE_OFF
  FIRMWARE_UPDATE
  DEVICE_ASSOCIATE
  REGISTERED_GPS
  REGISTERED_GPS_PREPAID
  SIGNAL_TIMEOUT
  SIGNAL_INTERRUPTED
  NO_GPS_SIGNAL
  LOW_TEMPERATURE
  HIGH_TEMPERATURE
  DEVICE_POSITION
  ACTIVE_SUBSCRIPTION
  ACTIVE_SUBSCRIPTION_TRIAL
  OFF_SUBSCRIPTION
  WEEKLY_GOAL_ACHIEVED
  WEEKLY_GOAL_ALMOST_REACHED
  PET_FOUND
  SET_PET_FOUND
  SET_PET_LOST
  QR_TAG_SCANNED
  REPLACEMENT
  DEVICE_OFFLINE
}

type PetHistoryExtra {
  address: String
  contentMessage: ContentMessage
  serialNumber: String
  newSerialNumber: String
}

input PetIn {
  name: String!
  birthDate: String
  species: SpeciesEnum!
  breedType: BreedTypeEnum!
  breeds: [String!]!
  gender: Gender!
  livingEnvironment: PetLivingEnvironment
  primaryColor: String
  weight: Float
  imageId: String
}

type PetlinkGps {
  id: String!
  entityType: EntityTypeEnum!
  serialNumber: String!
  petId: String!
  userId: String!
  creationDate: String!
  updateDate: String!
  countryCode: String
  timezone: String
  lastKnownPosition: GpsPosition
  lastKnownStatus: GpsStatus
  geofenceCoordinates: [Coordinates]
  newFirmwareVersion: NewFirmwareVersion
  settings: GpsSettings!
  subscriptionId: String
  subscriptionIsActive: Boolean
  logEnabled: Boolean
  endOfLifeDevice: Boolean
}

input PetlinkGpsIn {
  serialNumber: String!
  petId: String!
  countryCode: String
  timezone: String
}

type PetlinkMicrochip {
  id: String!
  entityType: EntityTypeEnum!
  serialNumber: String!
  petId: String!
  userId: String!
  creationDate: String!
  updateDate: String!
}

input PetlinkMicrochipIn {
  serialNumber: String!
  petId: String!
}

type PetlinkQrTag {
  id: String!
  entityType: EntityTypeEnum!
  serialNumber: String!
  petId: String
  userId: String!
  creationDate: String!
  updateDate: String!
}

input PetlinkQrTagIn {
  serialNumber: String!
  petId: String!
}

type PetlinkSubscription {
  id: String!
  status: SubscriptionStatusEnum!
  currentTermStart: String
  currentTermEnd: String
  nextBillingAt: String
  card: Card
  currencyCode: String!
  paymentStatus: PaymentStatusTypeEnum
  planChangeNotAllowed: Boolean!
  subscriptionItems: [PetlinkSubscriptionItem!]!
  billingPeriod: Int!
  billingPeriodUnit: String!
  addonToStopIds: [String!]
}

type PetlinkSubscriptionItem {
  amount: Int!
  name: String
  itemPriceId: String!
  itemType: String!
  quantity: Int!
  unitPrice: Int!
  itemId: String!
}

enum PetLivingEnvironment {
  INDOORS_AND_OUTOORS
  ALWAYS_AT_HOME
  ALWAYS_OUTDOORS
}

type PetProtection {
  id: String!
  petId: String
  userId: String!
  chargebeeSubscriptionId: String
  currentTermStart: String!
  currentTermEnd: String!
  status: PetProtectionStatus!
  petOwner: PetProtectionOwnerData
  pet: PetProtectionPetData
  petFlag: PetProtectionFlag!
  codiceTessera: String
  fileName: String
  name: String!
  price: Int!
  currencyCode: String!
  period: Int!
  periodUnit: String!
  reservedCoupon: String!
  reservedCouponPercent: Int!
  customerServiceContact: String!
  card: Card
}

type PetProtectionFlag {
  country: Boolean!
  age: Boolean!
}

type PetProtectionOwnerData {
  name: String!
  surname: String!
  email: String!
  fiscalCode: String!
  city: String!
  zipCode: String!
  streetAddress: String!
  countryCode: String!
  provinceCode: String!
  homePhone: String!
  mobilePhone: String!
}

input PetProtectionOwnerIn {
  name: String!
  surname: String!
  email: String!
  fiscalCode: String!
  city: String!
  zipCode: String!
  streetAddress: String!
  countryCode: String!
  provinceCode: String!
  homePhone: String!
  mobilePhone: String!
}

type PetProtectionPetData {
  species: String!
  breed: String!
  gender: String!
  name: String!
  birthDate: String
  microchip: String
}

input PetProtectionPetIn {
  species: String!
  breed: String!
  gender: String!
  name: String!
  birthDate: String!
  microchip: String
}

enum PetProtectionStatus {
  IN_PROGRESS
  ACTIVE
  REJECTED
  REFUNDED
  EXPIRED
  IN_REVIEW
  TO_UPDATE
  OPEN
  CANCELLED
}

type Plan {
  itemId: String!
  pricings: [Pricing]!
}

input Position {
  lat: Float!
  lng: Float!
}

enum PositionType {
  GPS
  LBS
  BLE
  WIFI
  SKIP
}

type Post {
  id: String!
  templateId: String!
  userId: String!
  countId: Int!
  title: String!
  description: String!
  imageUrl: String
  petType: String
}

type Pricing {
  id: String!
  name: String!
  externalName: String
  itemId: String!
  price: Float
  period: Float
  currencyCode: String!
  periodUnit: String
  itemFamilyId: String
  status: String
  trialPeriod: Int
  trialPeriodUnit: String
  addonPricings: [AddonPricing]
}

type Product {
  id: String!
  entityType: ProductTypeEnum!
  serialNumber: String!
  petId: String!
  userId: String!
  creationDate: String!
  updateDate: String!
  lastKnownPosition: GpsPosition

  """ TODO remove"""
  lastKnownStatus: GpsStatus

  """ TODO remove"""
  subscriptionIsActive: Boolean
  endOfLifeDevice: Boolean
}

enum ProductTypeEnum {
  PETLINK_MICROCHIP
  PETLINK_GPS
  PETLINK_QR_TAG
}

type Promotion {
  id: String!
  type: PromotionTypeEnum!
  name: String!
  currencyCode: String!
  price: Float!
  billingPeriod: Int!
  billingPeriodUnit: String!
}

input PromotionInput {
  id: String!
  type: PromotionTypeEnum!
}

enum PromotionTypeEnum {
  ADDON
}

type PurchasedService {
  id: String!
  creationDate: String!
  currentTermStart: String
  currentTermEnd: String
  card: Card
  currencyCode: String!
  paymentStatus: PaymentStatusTypeEnum
  invoice: InvoiceShortInfo
  subscriptionStatus: SubscriptionStatusEnum
}

type Query {
  getUser: ResponseUser!
  getPet(id: String!): ResponsePet!
  getPetByQrTag(serialNumber: String!): ResponsePetByQrTag!
  getPets: ResponsePets!
  getPetProtection(petProtectionId: String!): ResponseGetPetProtection!
  getPetHistory(petId: String!): ResponsePetHistory!
  getPetLostInfo(petId: String!): ResponseGetPetLostInfo!
  getPetlinkMicrochip(id: String!): ResponsePetlinkMicrochip!
  getPetlinkQrTag(id: String!): ResponsePetlinkQrTag!
  getPetlinkGps(id: String!): ResponsePetlinkGps!
  getProduct(id: String!, entityType: ProductTypeEnum!): ResponseProduct!
  getProducts(petId: String!): ResponseProducts!
  getGpsPromotions(productId: String!): ResponseGetGpsPromotions!

  """  end of life"""
  getEndOfLife(eolId: String, deviceId: String): ResponseGetEndOfLife!
  getPlansEOL(productId: String!, countryCode: String): ResponseGetPlansEOL!
  checkoutEOLNewDevice(eolId: String!): ResponseCheckoutEOLNewDevice!
  getSubscriptionPlans(productId: String, countryCode: String, serialNumber: String): ResponseSubscriptionPlans!
  getProtectionPlans(petId: String!): ResponseProtectionPlans!
  getSubscriptionPlanPricing(planPriceId: String!, careProtectionPlanId: String, addonPriceIds: [String!], countryCode: String!, productId: String!): ResponseSubscriptionPlanPricing!
  getPaymentSource: ResponseGetPaymentSource!
  getBillingInfo: ResponseBillingInfo!
  checkoutAddons(subscriptionId: String!, productId: String!, priceIds: [String!]!, hostedPageOptions: HostedPageOptionsInput): ResponseCheckoutAddons!
  checkoutNewSubscription(productId: String!, priceIds: [String!]!, hostedPageOptions: HostedPageOptionsInput): ResponseCheckoutNewSubscription!
  checkoutCareProtection(productId: String!, priceIds: [String!]!, hostedPageOptions: HostedPageOptionsInput): ResponseCheckoutCareProtection!
  checkoutPrepaid(orderId: String!, serialNumber: String!, priceIds: [String!]!, hostedPageOptions: HostedPageOptionsInput, appBrand: AppBrand): ResponseCheckoutNewSubscription!
  changeSubscriptionPlan(productId: String!, priceIds: [String!]!, hostedPageOptions: HostedPageOptionsInput): ResponseChangeSubscriptionPlan!
  getSubscriptions(productId: String!): ResponseGetSubscriptions!
  getPurchasedServices(productId: String!): ResponseGetPurchasedServices!
  getSubscriptionByProductId(productId: String!): ResponseGetSubscriptionByProductId!
  getOrder(orderId: String!): ResponseGetOrder
  getPetsAndProducts: ResponsePetsAndProducts!
  getNotificationsHistory(from: String, to: String): ResponseNotificationsHistory!
  getPositionsHistory(petId: String!, from: String, to: String): ResponsePositionsHistory!
  getPositionsHistoryDates(petId: String!, from: String, to: String): ResponsePositionsHistoryDates
  checkMicrochip(microchip: String!): ResponseCheckMicrochip!
  checkGps(serialNumber: String!): ResponseCheckGps!
  getDictionary(languageId: LanguageId, appBrand: AppBrand!): ResponseGetDictionary!
  getS3UploadUrl(fileName: String!): ResponseS3Upload!
  getLogUploadUrl(fileName: String!, deviceId: String!): ResponseGetLogUploadUrl!
  checkContact(contact: String!, contactType: ContactType!): Response!
  getCountryState(languageId: LanguageId, countryId: String): ResponseGetCountryState!
  getBreed(species: SpeciesEnum!, languageId: LanguageId): ResponseGetBreed!
  getColors(species: SpeciesEnum!, languageId: LanguageId): ResponseGetColors!
  getEnergySavingZone(id: String!): ResponseEnergySavingZone!
  getEnergySavingZones: ResponseEnergySavingZones!
  getGeofence(id: String!): ResponseGeofence!
  getGeofences: ResponseGeofences!
  getActivities(petId: String!, serialNumber: String, from: Int!, to: Int!): ResponseActivities!

  """  TODO: rename in dog"""
  getActivitiesAverage(petId: String!, serialNumber: String, from: Int!, to: Int!): ResponseActivities

  """  TODO: rename in dog"""
  getActivitiesByHour(petId: String!, serialNumber: String, from: Int!, to: Int!): ResponseActivitiesByHour!

  """  TODO: rename in dog"""
  getActivitiesCat(petId: String!, serialNumber: String, fromHealtRate: Int!, toHealtRate: Int!, fromActivities: Int!, toActivities: Int!): ResponseActivitiesCat!
  getActivitiesAverageCat(petId: String!, serialNumber: String, from: Int!, to: Int!): ResponseActivitiesAverageCat
  getActiveSubscriptions(subscriptionsIds: [String!]): ResponseActiveSubscriptions!
  getPosts(languageId: String, pagination: PaginationInput): ResponseGetPosts!

  """ sso"""
  getSsoToken(id: String!): ResponseSsoToken!
}

type Response {
  code: String!
  translationCode: String
  message: String!
}

type ResponseActiveSubscriptions {
  code: String!
  message: String!
  translationCode: String
  activeSubscriptions: [String]
}

type ResponseActivities {
  code: String!
  message: String!
  translationCode: String
  activityReport: ActivityReport
}

type ResponseActivitiesAverageCat {
  code: String!
  message: String!
  translationCode: String
  activityReport: ActivityReportAverageCat
}

type ResponseActivitiesByHour {
  code: String!
  message: String!
  translationCode: String
  activities: [Activities!]
}

type ResponseActivitiesCat {
  code: String!
  message: String!
  translationCode: String
  activityReport: ActivityReportCat
  highlights: Highlights
}

type ResponseBillingInfo {
  code: String!
  translationCode: String
  message: String!
  billingInfo: BillingInfo
}

type ResponseChangeSubscriptionPlan {
  code: String!
  message: String!
  url: String
  checkoutId: String
}

type ResponseCheckGps {
  code: String!
  translationCode: String
  message: String!
  imei: String
  idccd: String
  planProfileId: String
  brand: String
  model: String
  firmwareVersion: String
  simStatus: String
  simRequestedStatus: String
}

type ResponseCheckMicrochip {
  code: String!
  translationCode: String
  message: String!
  pet: PetCheckMicrochip
}

type ResponseCheckoutAddons {
  code: String!
  message: String!
  url: String
  checkoutId: String
}

type ResponseCheckoutCareProtection {
  code: String!
  message: String!
  url: String
  checkoutId: String
}

type ResponseCheckoutEOLNewDevice {
  code: String!
  message: String!
  url: String
}

type ResponseCheckoutNewSubscription {
  code: String!
  message: String!
  url: String
  checkoutId: String
}

type ResponseCreatePetlinkGps {
  code: String!
  translationCode: String
  message: String!
  petlinkGps: PetlinkGps
  currentTermEnd: String
  url: String
}

type ResponseEnergySavingZone {
  code: String!
  message: String!
  translationCode: String
  energySavingZone: EnergySavingZone
}

type ResponseEnergySavingZones {
  code: String!
  message: String!
  translationCode: String
  energySavingZones: [EnergySavingZone!]
}

type ResponseGeofence {
  code: String!
  message: String!
  translationCode: String
  geofence: Geofence
}

type ResponseGeofences {
  code: String!
  message: String!
  translationCode: String
  geofences: [Geofence!]
}

type ResponseGetBreed {
  code: String!
  translationCode: String
  message: String!
  items: [Breed!]
}

type ResponseGetColors {
  code: String!
  translationCode: String
  message: String!
  items: [Color!]
}

type ResponseGetCountryState {
  code: String!
  translationCode: String
  message: String!
  items: [CountryState!]
}

type ResponseGetDictionary {
  code: String!
  translationCode: String
  message: String!
  dictionary: String!
}

type ResponseGetEndOfLife {
  code: String!
  message: String!
  translationCode: String
  endOfLifeItem: EndOfLife
}

type ResponseGetGpsPromotions {
  code: String!
  translationCode: String
  message: String!
  promotions: [Promotion]
}

type ResponseGetLogUploadUrl {
  code: String!
  translationCode: String
  message: String!
  uploadData: UploadData
}

type ResponseGetOrder {
  code: String!
  message: String!
  translationCode: String
  order: Order
}

type ResponseGetPaymentSource {
  code: String!
  message: String!
  status: PaymentSourceStatus
}

type ResponseGetPetLostInfo {
  code: String!
  translationCode: String
  message: String!
  lostInfo: LostInfo
}

type ResponseGetPetProtection {
  code: String!
  translationCode: String
  message: String!
  petProtection: PetProtection
}

type ResponseGetPlansEOL {
  code: String!
  translationCode: String
  message: String!
  plans: [Plan!]
  devicePrice: [DevicePrice!]
  endOfLife: EndOfLife
}

type ResponseGetPosts {
  code: String!
  message: String!
  translationCode: String
  items: [Post!]!
  pagination: Pagination!
}

type ResponseGetPurchasedServices {
  code: String!
  message: String!
  translationCode: String
  purchasedServices: [PurchasedService!]
}

type ResponseGetSubscriptionByProductId {
  code: String!
  message: String!
  translationCode: String
  subscription: PetlinkSubscription
}

type ResponseGetSubscriptions {
  code: String!
  message: String!
  translationCode: String
  subscriptions: [SubscriptionShortInfo!]
}

type ResponseManagePaymentSources {
  code: String!
  message: String!
  url: String
}

type ResponseNotificationSettings {
  code: String!
  translationCode: String
  message: String!
  notificationSettings: NotificationSettings
}

type ResponseNotificationsHistory {
  code: String!
  translationCode: String
  message: String!
  notifications: [Notification!]
}

type ResponseOtp {
  code: String!
  translationCode: String
  message: String!
  verificationId: String
}

type ResponsePet {
  code: String!
  translationCode: String
  message: String!
  pet: Pet
}

type ResponsePetByQrTag {
  code: String!
  translationCode: String
  message: String!
  pet: Pet
  user: User
}

type ResponsePetHistory {
  code: String!
  translationCode: String
  message: String!
  petHistory: [PetHistoryEvent!]
}

type ResponsePetlinkGps {
  code: String!
  translationCode: String
  message: String!
  petlinkGps: PetlinkGps
}

type ResponsePetlinkMicrochip {
  code: String!
  translationCode: String
  message: String!
  petlinkMicrochip: PetlinkMicrochip
}

type ResponsePetlinkQrTag {
  code: String!
  translationCode: String
  message: String!
  petlinkQrTag: PetlinkQrTag
}

type ResponsePets {
  code: String!
  translationCode: String
  message: String!
  pets: [Pet!]
}

type ResponsePetsAndProducts {
  code: String!
  translationCode: String
  message: String!
  pets: [Pet!]
  products: [Product!]
}

type ResponsePositionsHistory {
  code: String!
  translationCode: String
  message: String!
  positions: [GpsPosition!]
}

type ResponsePositionsHistoryDates {
  code: String!
  message: String!
  translationCode: String
  dates: [String]
}

type ResponseProduct {
  code: String!
  translationCode: String
  message: String!
  verificationId: String
  product: Product
}

type ResponseProducts {
  code: String!
  translationCode: String
  message: String!
  products: [Product!]
}

type ResponseProtectionPlans {
  code: String!
  translationCode: String
  message: String!
  careProtectionPlans: [CareProtectionPlan!]
}

type ResponseReplacement {
  code: String!
  message: String!
  translationCode: String
  product: Product
}

type ResponseS3Upload {
  code: String!
  translationCode: String
  message: String!
  uploadData: UploadData
  command: [String!]
}

type ResponseSendSetting {
  code: String!
  translationCode: String
  message: String!
  petlinkGps: PetlinkGps
  energySavingZone: EnergySavingZone
}

type ResponseSetPetIsFound {
  code: String!
  translationCode: String
  message: String!
}

type ResponseSetPetIsLost {
  code: String!
  translationCode: String
  message: String!
  lostInfo: LostInfo
}

type ResponseSsoToken {
  code: String!
  message: String!
  translationCode: String
  ssoToken: String
}

type ResponseSsoUrl {
  code: String!
  message: String!
  translationCode: String
  url: String
}

type ResponseSubscriptionPlanPricing {
  code: String!
  translationCode: String
  message: String!
  pricing: Pricing
  careProtectionPricing: Pricing
  trialDuration: Int
  paymentMethodRequired: Boolean
  coupon: Coupon
}

type ResponseSubscriptionPlans {
  code: String!
  translationCode: String
  message: String!
  plans: [Plan!]
  careProtectionPlans: [CareProtectionPlan!]
  trialDuration: Int
  paymentMethodRequired: Boolean
  coupon: Coupon
}

type ResponseUpdateEndOfLife {
  code: String!
  message: String!
  translationCode: String
  endOfLifeItem: EndOfLife
}

type ResponseUpdatePaymentSources {
  code: String!
  message: String!
  url: String
}

type ResponseUpdatePetProtectionData {
  code: String!
  translationCode: String
  message: String!
  petProtection: PetProtection
}

type ResponseUser {
  code: String!
  translationCode: String
  message: String!
  user: User
}

type ResponseUtilityIntegrationTest {
  code: String!
  message: String!
  userId: String
}

input Setting {
  operationType: SettingOperationEnum!
  settingType: SettingTypeEnum!
  deviceId: String
  geofence: [CoordinatesIn]
  id: String

  """  id and deviceId both used for activation ESZ and eventually others"""
  updateObject: AWSJSON
  createObject: AWSJSON
}

enum SettingOperationEnum {
  CREATE
  UPDATE
  DELETE
  ACTIVATE
  DEACTIVATE
}

enum SettingTypeEnum {
  GEOFENCE
  ENERGY_SAVING_ZONE
  UPDATE_FREQUENCY
}

type ShippingAddress {
  firstName: String!
  lastName: String!
  address: String!
  province: String!
  country: String!
  city: String!
  zip: String!
}

input ShippingAddressIn {
  firstName: String!
  lastName: String!
  address: String!
  province: String!
  country: String!
  city: String!
  zip: String!
}

enum SpeciesEnum {
  DOG
  CAT
  OTHER
}

enum StatusState {
  ON
  OFF
  REQUESTED
  ERROR
}

type Subscription {
  onSendingOtp(verificationId: String): ResponseOtp
  onGpsMessagePosition(id: String!): GpsMessagePosition
  onGpsMessageStatus(id: String!): GpsMessageStatus
  onSubscriptionStatus(id: String!): SubscriptionMessageStatus
}

type SubscriptionMessageStatus {
  id: String!
  status: SubscriptionStatus!
}

input SubscriptionMessageStatusIn {
  id: String!
  status: SubscriptionStatusIn!
}

type SubscriptionShortInfo {
  card: Card
  creationDate: String!
  currencyCode: String!
  currentTermEnd: String
  currentTermStart: String
  id: String!
  invoice: InvoiceShortInfo
  paymentStatus: PaymentStatusTypeEnum
  planChangeNotAllowed: Boolean!
  status: SubscriptionStatusEnum!
  subscriptionItems: [SubscriptionShortInfoItem!]!
  totalAmount: Float!
  billingPeriod: Int!
  billingPeriodUnit: String!
  addonToStopIds: [String!]
}

type SubscriptionShortInfoItem {
  amount: Float!
  quantity: Float!
  name: String
  unitPrice: Float!
  itemType: String!
  itemPriceId: String!
  itemId: String!
}

type SubscriptionStatus {
  productId: String!
  subscriptionIsActive: Boolean!
  currentTermEnd: String!
}

enum SubscriptionStatusEnum {
  to_stop_renew
  to_stop_renew_addon
  transferred
  cancelled
  paused
  non_renewing
  future
  in_trial
  active
  closed
}

input SubscriptionStatusIn {
  productId: String!
  subscriptionIsActive: Boolean!
  currentTermEnd: String!
}

input UpdateBillingInfoInput {
  firstName: String!
  lastName: String!
  email: String!
  phone: String!
  billingInfo: BillingInfoInput!
}

input UpdateEnergySavingZoneIn {
  id: String!
  entityType: EntityTypeEnum!
  ssid: String!
  bssid: String!
  icon: String!
  name: String!
  position: CoordinatesIn!
  radius: Float!
}

input UpdateGeofenceIn {
  id: String!
  name: String!
  position: [CoordinatesIn!]!
}

input UpdateNotificationSettingsInput {
  energySavingZone: EszNotificationsInput!
}

input UpdatePetIn {
  id: String!
  name: String
  birthDate: String
  species: SpeciesEnum
  breedType: BreedTypeEnum
  breeds: [String!]
  gender: Gender
  primaryColor: String
  weight: Float
  imageId: String
  neutered: Boolean
  livingEnvironment: PetLivingEnvironment
  length: Float
}

input UpdatePetlinkGpsIn {
  id: String!
  countryCode: String
  timezone: String
  settings: GpsSettingsIn
}

input UpdateUserIn {
  id: String!
  name: String!
  surname: String!
  birthDate: String
  gender: Gender
  city: String!
  countryCode: String!
  zipCode: String
  streetAddress: String
  stateCode: String
  languageId: LanguageId!
  imageId: String
  timezone: String
  settings: UserSettingsIn
  notificationSettings: NotificationSettingsIn
}

type UploadData {
  id: String!
  url: String!
}

type User {
  id: String!
  entityType: EntityTypeEnum!
  email: String!
  name: String!
  surname: String!
  city: String
  stateCode: String
  zipCode: String
  streetAddress: String
  countryCode: String!
  phone: String!
  birthDate: String
  gender: Gender
  languageId: LanguageId!
  creationDate: String!
  updateDate: String!
  notificationSettings: NotificationSettings!
  mobileDevices: [MobileDevice!]
  contactVerified: ContactVerified
  haveMicrochip: Boolean
  image: Image
  timezone: String
  settings: UserSettings!
  chargebeeId: String
  safetyTermsCat: Boolean
  migrated: Boolean
}

input UserIn {
  email: String!
  name: String!
  surname: String!
  city: String!
  countryCode: String!
  zipCode: String
  streetAddress: String
  stateCode: String
  phone: String!
  password: String!
  confirmPassword: String!
  languageId: LanguageId!
  timezone: String
}

type UserSettings {
  liveTrack: Boolean!
  liveSpeed: Boolean!
  liveDistance: Boolean!
}

input UserSettingsIn {
  liveTrack: Boolean!
  liveSpeed: Boolean!
  liveDistance: Boolean!
}

input UtilityIntegrationTestInput {
  utilityType: UtilityTestTypeEnum!
  phone: String
  productId: String
  priceIds: [String!]
  userIn: UserIn
  appBrand: AppBrand
}

enum UtilityTestTypeEnum {
  CLEAN_UP_USER
  BUY_NEW_SUBSCRIPTION
  SIGN_UP
}

enum ValidationStatusEnum {
  not_validated
  valid
  partially_valid
  invalid
}

