name: test-petlink-infrastrucutre

on:
  push:
    branches: [ develop ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      #clone code inside virtual machine
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment based on branch
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENV_MODE=develop" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "ENV_MODE=test" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: docker build -t petlink-everywhere-test .

      - name: Run integration tests
        env:
          # Core API
          CORE_GRAPHQL_API_URL: ${{ secrets.CORE_GRAPHQL_API_URL }}
          CORE_GRAPHQL_API_KEY: ${{ secrets.CORE_GRAPHQL_API_KEY }}
          # CCT API
          CCT_GRAPHQL_API_URL: ${{ secrets.CCT_GRAPHQL_API_URL }}
          CCT_GRAPHQL_API_KEY: ${{ secrets.CCT_GRAPHQL_API_KEY }}
          # AWS Cognito
          COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
          COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          # AWS IAM
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # User
          USER_PHONE_NUMBER: ${{ secrets.USER_PHONE_NUMBER }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          # Twilio
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          # Gmail
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REDIRECT_URI: ${{ secrets.GMAIL_REDIRECT_URI }}
          GMAIL_ACCESS_TOKEN: ${{ secrets.GMAIL_ACCESS_TOKEN }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
        run: |
          docker run \
            -e CORE_GRAPHQL_API_URL \
            -e CORE_GRAPHQL_API_KEY \
            -e CCT_GRAPHQL_API_URL \
            -e CCT_GRAPHQL_API_KEY \
            -e COGNITO_REGION \
            -e COGNITO_CLIENT_ID \
            -e AWS_REGION \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e USER_PHONE_NUMBER \
            -e USER_EMAIL \
            -e USER_PASSWORD \
            -e TWILIO_ACCOUNT_SID \
            -e TWILIO_AUTH_TOKEN \
            -e GMAIL_CLIENT_ID \
            -e GMAIL_CLIENT_SECRET \
            -e GMAIL_REDIRECT_URI \
            -e GMAIL_ACCESS_TOKEN \
            -e GMAIL_REFRESH_TOKEN \
            -e NODE_ENV=${{ steps.set-env.outputs.ENV_MODE }} \
            petlink-everywhere-test yarn test:${{ steps.set-env.outputs.ENV_MODE }}:run
